# Nornir Hosts File 
---
CORE:
  hostname: 192.168.43.10
  groups: 
    - Switches

SW1:
  hostname: 192.168.43.11
  groups:
    - Switches

SW3:
  hostname: 192.168.43.12
  groups:
    - Switches

SW4:
  hostname: 192.168.43.13
  groups:
    - Switches
